
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CourseExamSetting
    {
        [Key()]
        public int ID { get; set; }
        public Nullable<int> CourseListID { get; set; }
        public Nullable<int> ExamTypeID { get; set; }
        public Nullable<int> NumberingID { get; set; }
        public Nullable<int> ExamTime { get; set; }
        public Nullable<int> Criteria { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> QuestionQty { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<int> BeginnerQty { get; set; }
        public Nullable<int> IntermediatesQty { get; set; }
        public Nullable<int> ExpertsQty { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   
    }

}
