
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CourseAssign
    {
        [Key()]
        public int AssignID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> DivID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> WorkID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    public virtual Course Course { get; set; }

    public virtual MSDepartment MSDepartment { get; set; }

    public virtual MSDivision MSDivision { get; set; }

    public virtual MSPosition MSPosition { get; set; }

    public virtual UserManagement UserManagement { get; set; }

    }

}
