
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Course
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.CourseAssigns = new HashSet<CourseAssign>();

    }

        [Key()]
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CourseLocationID { get; set; }
        public string CourseType { get; set; }
        public string Name_L1 { get; set; }
        public string Name_L2 { get; set; }
        public string Name_L3 { get; set; }
        public string Name_L4 { get; set; }
        public string Object_L1 { get; set; }
        public string Object_L2 { get; set; }
        public string Object_L3 { get; set; }
        public string Object_L4 { get; set; }
        public string Intro_L1 { get; set; }
        public string Intro_L2 { get; set; }
        public string Intro_L3 { get; set; }
        public string Intro_L4 { get; set; }
        public string Target_L1 { get; set; }
        public string Target_L2 { get; set; }
        public string Target_L3 { get; set; }
        public string Target_L4 { get; set; }
        public string Criteria_L1 { get; set; }
        public string Criteria_L2 { get; set; }
        public string Criteria_L3 { get; set; }
        public string Criteria_L4 { get; set; }
        public Nullable<int> Previous { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string CourseImage { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CourseAssign> CourseAssigns { get; set; }

    public virtual MSCategory MSCategory { get; set; }

    public virtual MSCourseLocation MSCourseLocation { get; set; }

    }

}
