
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ExamAnswer
    {
        [Key()]
        public int AnsID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnsNo { get; set; }
        public string AnsText_L1 { get; set; }
        public string AnsText_L2 { get; set; }
        public string AnsText_L3 { get; set; }
        public string AnsText_L4 { get; set; }
        public string AnsCorrect { get; set; }
        public string AnsKey { get; set; }
        public string AnsSensitive { get; set; }
        public Nullable<int> AnsPosition { get; set; }
        public string AnsScore { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    public virtual Question Question { get; set; }

    }

}
