
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [Key()]
        public int ID { get; set; }
        public string Title_L1 { get; set; }
        public string Title_L2 { get; set; }
        public string Title_L3 { get; set; }
        public string Title_L4 { get; set; }
        public Nullable<int> ExamTypeID { get; set; }
        public Nullable<int> CourseListID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   
    }

}
