
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ExaminationDetail
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ExaminationDetail()
    {

        this.Questions = new HashSet<Question>();

    }

        [Key()]
        public string ID { get; set; }
        public Nullable<int> ExamHID { get; set; }
        public Nullable<int> QuestionQTY { get; set; }
        public string QuestionRandom { get; set; }
        public Nullable<int> AnswerQTY { get; set; }
        public string AnswerRandom { get; set; }
        public string AnsTypeID { get; set; }
        public string ExamTime { get; set; }
        public string PassCriteria { get; set; }
        public string ActiveStatus { get; set; }
        public string TotalScore { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    public virtual MSAnswerType MSAnswerType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Question> Questions { get; set; }

    }

}
