
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class MediaStorage
    {
        [Key()]
        public int MediaID { get; set; }
        public string MediaType { get; set; }
        public string Path { get; set; }
        public Nullable<int> RefProcessCode { get; set; }
        public string RefType { get; set; }
   
    }

}
