
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Question
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Question()
    {

        this.ExamAnswers = new HashSet<ExamAnswer>();

    }

        [Key()]
        public int QuestionID { get; set; }
        public string ExamID { get; set; }
        public Nullable<int> QusNo { get; set; }
        public string QusText_L1 { get; set; }
        public string QusText_L2 { get; set; }
        public string QusText_L3 { get; set; }
        public string QusText_L4 { get; set; }
        public Nullable<double> QusScore { get; set; }
        public string QusLevel { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamAnswer> ExamAnswers { get; set; }

    public virtual ExaminationDetail ExaminationDetail { get; set; }

    }

}
