
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class TextResource
    {
        [Key()]
        public int Id { get; set; }
        public string Module { get; set; }
        public string Code { get; set; }
        public string L1Value { get; set; }
        public string L2Value { get; set; }
        public string L3Value { get; set; }
        public string L4Value { get; set; }
        public Nullable<bool> IsActive { get; set; }
   
    }

}
