
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ESN.Model
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class UserHistorical
    {
        [Key()]
        public int UserHisID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<double> TopScore { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> CourseListID { get; set; }
        public Nullable<System.DateTime> LearnTime { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
   


    public virtual UserManagement UserManagement { get; set; }

    }

}
